# options:
#    auto-update - Auto check and update from Github for new versions
#    armor-update-interval - Update interval for Slimefun armor effects
#    enable-armor-effects - Enable/disable armor effects
#    chat-prefix - Prefix for all Slimefun messages
#    auto-save-delay-in-minutes - Auto-save data interval in minutes
#    legacy-ore-washer - Use legacy ore washer mechanism
#    legacy-dust-washer - Use legacy dust washer mechanism
#    legacy-ore-grinder - Use legacy ore grinder mechanism
#    language - Slimefun text language (excluding items)
#    enable-translations - Enable multi-language support
#    backwards-compatibility - Item backwards compatibility mode, disabling this will use new item system
#                             and improve performance
#    log-duplicate-block-entries - Log warnings for duplicate block entries
#    burn-players-when-radioactive - Burn players when exposed to radiation
#    drop-excess-sf-give-items - Drop excess items when giving Slimefun items via command with full inventory
#    backup-data - Auto backup data
#    bypass-environment-check - Bypass compatibility check (Warning: Issues won't be accepted if enabled)
options:
  auto-update: true
  chat-prefix: '&a&lSlimefun 4 &7> '
  armor-update-interval: 10
  enable-armor-effects: true
  enable-radiation: true
  radiation-update-interval: 1
  radiation-grace-period: 15
  rainbow-armor-update-interval: 3
  auto-save-delay-in-minutes: 10
  legacy-ore-washer: false
  legacy-dust-washer: false
  legacy-ore-grinder: true
  language: en
  enable-translations: true
  log-duplicate-block-entries: true
  burn-players-when-radioactive: true
  drop-excess-sf-give-items: false
  backup-data: true
  drop-block-creative: true
  bypass-environment-check: false
  bypass-item-length-check: false
  max-gps-waypoints: 21

guide:
  # Show vanilla item recipes in the guide
  show-vanilla-recipes: true
  # Automatically give the Slimefun guide when a player joins the server for the first time
  receive-on-first-join: true
  # Show hidden item groups in search
  show-hidden-item-groups-in-search: false

researches:
  # Allow creative mode players to unlock researches for free
  free-in-creative-mode: true
  # Enable fireworks when unlocking researches
  enable-fireworks: true
  # Use money instead of experience to unlock researches
  use-money-unlock: false
  # Experience to money conversion rate
  currency-cost-convert-rate: 25.0
  # Disable learning animation when unlocking researches
  disable-learning-animation: false

URID:
  info-delay: 3000
  custom-ticker-delay: 10
  enable-tickers: true

networks:
  max-size: 200
  cargo-ticker-delay: 0
  enable-visualizer: true
  delete-excess-items: false

talismans:
  use-actionbar: true

metrics:
  auto-update: false

backpack:
  # Allow backpacks to be opened when the owner is offline
  allow-open-when-owner-offline: true

research-ranks:
  - Chicken
  - Cow
  - Spider
  - Villager
  - Explorer
  - Student
  - Intern
  - Apprentice
  - Novice Apprentice
  - Skilled Apprentice
  - Mage Apprentice
  - Distinguished Mage
  - Young Magician
  - Clumsy Magician
  - Common Magician
  - Skilled Magician
  - Master Magician
  - Acrobat Magician
  - Habitual Magician
  - Distinguished Magician
  - Clumsy Wizard
  - Wizard
  - Common Wizard
  - Acrobat Wizard
  - Distinguished Wizard
  - Excellent Wizard
  - Young Master
  - Clumsy Master
  - Intern Master
  - Qualified Master
  - Master
  - Acrobat Master
  - Distinguished Master
  - Excellent Master
  - Proficient Master
  - Chosen One
